In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
net = nn.Sequential(
    nn.Linear(20, 256),
    nn.ReLU(),
    nn.Linear(256, 10)
)

In [3]:
X = torch.rand(1, 20)
Y = torch.rand(2, 20)
net(X), net(Y)

(tensor([[ 0.0305, -0.0268, -0.3276, -0.3177, -0.0072, -0.1315, -0.0188, -0.1975,
           0.1187,  0.1847]], grad_fn=<AddmmBackward0>),
 tensor([[ 0.1634, -0.0096, -0.2774, -0.2480,  0.0960, -0.0553, -0.0903, -0.2894,
           0.0078,  0.1538],
         [ 0.0478, -0.0257, -0.2367, -0.1661,  0.0684,  0.0286, -0.0058, -0.1293,
          -0.0313,  0.1844]], grad_fn=<AddmmBackward0>))

In [4]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__() # 等价于nn.Module.__init__(self)
        self.hidden = nn.Linear(20, 256) # 隐藏层
        self.out = nn.Linear(256, 10) # 输出层
    
    # 定义模型的正向传播，即如何根据输入X返回所需要的模型输出
    def forward(self, X):
        return self.out(F.relu(self.hidden(X))) 

In [5]:
net = MLP()
net(X), net(Y)

(tensor([[ 0.0121,  0.0106, -0.0644,  0.0085,  0.1578, -0.0501, -0.1041,  0.1122,
           0.2763,  0.1812]], grad_fn=<AddmmBackward0>),
 tensor([[ 0.0218,  0.1357, -0.0567, -0.0195,  0.1813, -0.1347, -0.1338,  0.1635,
           0.2653,  0.1562],
         [-0.0047,  0.1565, -0.0608,  0.0995,  0.2227, -0.2021, -0.1654,  0.0637,
           0.2162,  0.1245]], grad_fn=<AddmmBackward0>))

In [6]:
class MySequential(nn.Module):
    def __init__(self, *args):
        super().__init__()
        for block in args:
            # 这里，`block`是`Module`子类的一个实例。我们把它保存在'Module'类的成员变量
            # `_children` 中。`block`的类型是OrderedDict。
            self._modules[block] = block
    def forward(self, X):
        # OrderedDict保证了按照成员添加时的顺序遍历它们
        for block in self._modules.values():
            X = block(X)
        return X

In [7]:
X = torch.arange(16, dtype= torch.float32).reshape(1,1,4,4)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [8]:
pool2d = nn.MaxPool2d(3,padding=1)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])